# Experimentation

## Data Ingestion

In [1]:
import os
import pandas as pd

In [2]:
pwd

'/Users/macbook/Documents/workspace_datahackerman/tesco_customer_churn'

In [3]:
FILE_NAME = "CustomerChurn.csv"
DATA_FOLDER = "data"

In [4]:
main_path = os.getcwd()
main_path

'/Users/macbook/Documents/workspace_datahackerman/tesco_customer_churn'

In [5]:
file_path = os.path.join(os.path.join(main_path, DATA_FOLDER), FILE_NAME)
file_path

'/Users/macbook/Documents/workspace_datahackerman/tesco_customer_churn/data/CustomerChurn.csv'

In [6]:
%%time

churn_data = pd.read_csv(file_path)

CPU times: user 43 ms, sys: 11.8 ms, total: 54.8 ms
Wall time: 66.9 ms

In [7]:
churn_data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Adjust column headers to lowercase

In [100]:
churn_data.columns = map(str.lower, churn_data.columns)

In [101]:
churn_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [102]:
churn_data.shape

(7043, 21)

## Data Inspection

In [105]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   object
 1   gender            7043 non-null   object
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   object
 4   dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   object
 7   multiplelines     7043 non-null   object
 8   internetservice   7043 non-null   object
 9   onlinesecurity    7043 non-null   object
 10  onlinebackup      7043 non-null   object
 11  deviceprotection  7043 non-null   object
 12  techsupport       7043 non-null   object
 13  streamingtv       7043 non-null   object
 14  streamingmovies   7043 non-null   object
 15  contract          7043 non-null   object
 16  paperlessbilling  7043 non-null   object
 17  paymentmethod     7043 non-null   object
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

Only tenure , monthlycharges and totalcharges are Numerical Variables.

churndata.totalcharges data type needs modification

to unify decimal places with Monthly and modify to float data type

In [107]:
churn_data["totalcharges"] = churn_data["totalcharges"].astype(float)

In [108]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   object
 1   gender            7043 non-null   object
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   object
 4   dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   object
 7   multiplelines     7043 non-null   object
 8   internetservice   7043 non-null   object
 9   onlinesecurity    7043 non-null   object
 10  onlinebackup      7043 non-null   object
 11  deviceprotection  7043 non-null   object
 12  techsupport       7043 non-null   object
 13  streamingtv       7043 non-null   object
 14  streamingmovies   7043 non-null   object
 15  contract          7043 non-null   object
 16  paperlessbilling  7043 non-null   object
 17  paymentmethod     7043 non-null   object
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [109]:
churn_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [110]:
churn_data.tail()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

to check for missing values

In [111]:
churn_data.isna().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

to check for duplicates

In [113]:
churn_data.duplicated().sum()

0

## Exploratory Data Analysis

. Statistical Analysis
. Plots
. Correlation

To compute basic descriptive statistics

Calculate average tenure

In [114]:
churn_data["tenure"].mean()

32.37114865824223

Calculate average monthly charge

In [115]:
churn_data["monthlycharges"].mean()

64.76169246059918

Calculate average total charge

In [116]:
churn_data["totalcharges"].mean()

2279.7343035638223

Aggregate tenure, Monthly Charges and Total Charges by gender

In [117]:
churn_data[["gender", "tenure"]].groupby("gender").mean()

           tenure
gender
Female  32.244553
Male    32.495359

In [120]:
churn_data[["gender", "monthlycharges"]].groupby("gender").mean()

        monthlycharges
gender
Female       65.204243
Male         64.327482

In [121]:
churn_data[["gender", "totalcharges"]].groupby("gender").mean()

        totalcharges
gender
Female   2279.918062
Male     2279.554008

Create additional columns

In [123]:
churn_data.tenure.min(),churn_data.tenure.max()

(0, 72)

In [124]:
churn_data.monthlycharges.min(),churn_data.monthlycharges.max()

(18.25, 118.75)

In [125]:
churn_data.totalcharges.min(),churn_data.totalcharges.max()

(0.0, 8684.8)

Group customers based on tenure

In [27]:
# churn_data["tenure_group"]=pd.cut(churn_data["tenure"],
#      bins=[-1,25,48,73],labels=['Low','Medium','High'])

In [28]:
# churn_data["MonthlyCharges_group"]=pd.cut(churn_data["tenure"],
#                                  bins=[18,52,85,119],labels=['Low','Medium','High'])

In [29]:
#churn_data["TotalCharges_group"]=pd.cut(churn_data["TotalCharges"],
 #                                 bins=[0,2895,5790,8685],labels=['Low','Medium','High'])

In [126]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   object
 1   gender            7043 non-null   object
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   object
 4   dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   object
 7   multiplelines     7043 non-null   object
 8   internetservice   7043 non-null   object
 9   onlinesecurity    7043 non-null   object
 10  onlinebackup      7043 non-null   object
 11  deviceprotection  7043 non-null   object
 12  techsupport       7043 non-null   object
 13  streamingtv       7043 non-null   object
 14  streamingmovies   7043 non-null   object
 15  contract          7043 non-null   object
 16  paperlessbilling  7043 non-null   object
 17  paymentmethod     7043 non-null   object
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [127]:
churn_data.sample(5)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
6805,4323-OHFOW,Female,1,Yes,No,70,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),105.55,7195.35,No
6852,2408-PSJVE,Male,0,Yes,Yes,44,Yes,No,DSL,No,...,Yes,Yes,No,No,Month-to-month,Yes,Mailed check,61.90,2924.05,No
5177,3672-YITQD,Male,1,Yes,No,36,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,84.10,3021.60,Yes
4428,5449-FIBXJ,Male,0,Yes,Yes,19,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,No,Electronic check,103.30,2012.70,Yes
642,0970-ETWGE,Male,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,89.55,89.55,Yes

In [32]:
# Compute average tenure charge per customer

In [33]:
# def calculate_average_tenure_charge(TotalCharges,tenure):
   # """This function calculates average tenure charge per customer"""

   # result = churn_data["TotalCharges"] /churn_data["tenure"]

 #   return result

In [34]:
# churn_data["AverageTenureCharge"] = calculate_average_tenure_charge

In [35]:
# churn_data.head()

In [36]:
# churn_data.AverageTenureCharge = churn_data.AverageTenureCharge.str.replace(' ','0')

In [37]:
# churn_data["AverageTenureCharge"] = churn_data["AverageTenureCharge"].astype(float)

In [128]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   object
 1   gender            7043 non-null   object
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   object
 4   dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   object
 7   multiplelines     7043 non-null   object
 8   internetservice   7043 non-null   object
 9   onlinesecurity    7043 non-null   object
 10  onlinebackup      7043 non-null   object
 11  deviceprotection  7043 non-null   object
 12  techsupport       7043 non-null   object
 13  streamingtv       7043 non-null   object
 14  streamingmovies   7043 non-null   object
 15  contract          7043 non-null   object
 16  paperlessbilling  7043 non-null   object
 17  paymentmethod     7043 non-null   object
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [129]:
churn_data.sample(5)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
2874,8347-GDTMP,Female,0,Yes,No,64,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.45,1225.65,No
2643,3550-SAHFP,Female,0,No,No,33,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,83.35,2757.85,Yes
5079,2507-QZPQS,Male,0,No,No,15,Yes,Yes,Fiber optic,No,...,No,Yes,No,Yes,Month-to-month,No,Electronic check,95.70,1451.10,No
3794,4280-DLSHD,Male,0,Yes,No,8,Yes,No,DSL,No,...,Yes,No,No,No,Month-to-month,Yes,Mailed check,54.75,445.85,No
6708,2272-QAGFO,Female,1,No,No,14,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.30,1096.25,Yes

## Model Building

In [132]:
#churn_data.sample()

## Prepare Dataset for Modelling

In [133]:
churn_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Train_Test_Split

In [134]:
# 0.3, 0.7

In [135]:
from sklearn.model_selection import train_test_split

In [136]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [137]:
# y = mX + c

In [138]:
X = churn_data[["customerid","gender","seniorcitizen",
                "partner","dependents","tenure",
                "phoneservice","multiplelines","internetservice",
                "onlinesecurity","deviceprotection","techsupport",
                "streamingtv","streamingmovies","contract",
                "paperlessbilling","paymentmethod",
                "monthlycharges","totalcharges"]]

In [139]:
type(X)

pandas.core.frame.DataFrame

In [140]:
X.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [141]:
y = churn_data["churn"]

In [142]:
type(y)

pandas.core.series.Series

In [143]:
y.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: churn, dtype: object

In [144]:
y[0:5]

0     No
1     No
2    Yes
3     No
4    Yes
Name: churn, dtype: object

In [145]:
train_data, test_data = train_test_split(churn_data,test_size = 0.30, random_state =42)

In [146]:
train_data.shape, test_data.shape

((4930, 21), (2113, 21))

In [147]:
train_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
1695,4906-ZHGPK,Male,0,Yes,Yes,54,Yes,Yes,DSL,No,...,No,Yes,Yes,No,One year,Yes,Electronic check,70.70,3770.00,No
1095,7439-DKZTW,Male,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.55,80.55,No
3889,2592-HODOV,Male,0,No,No,13,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.30,259.65,No
3667,7826-VVKWT,Female,1,Yes,Yes,24,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,Yes,Electronic check,96.55,2263.45,No
2902,1658-TJVOA,Female,1,No,No,6,Yes,No,Fiber optic,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.10,450.90,No

In [148]:
test_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.80,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.70,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.10,No

In [149]:
label = 'churn'

In [69]:
print("Summary of churn variable:\n", train_data[label].describe())

Summary of churn variable:
 count     4930
unique       2
top         No
freq      3635
Name: churn, dtype: object

## basic model build

In [166]:
%%time

save_path = 'agModels-predictchurn'
predictor = TabularPredictor(label=label, path=save_path).fit(train_data)

Warning: path already exists! This predictor may overwrite an existing predictor! path="agModels-predictchurn"
Beginning AutoGluon training ...
AutoGluon will save models to "agModels-predictchurn/"
AutoGluon Version:  0.7.0
Python Version:     3.9.16
Operating System:   Darwin
Platform Machine:   x86_64
Platform Version:   Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
Train Data Rows:    4930
Train Data Columns: 20
Label Column: churn
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['No', 'Yes']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 = Yes, class 0 = No
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5196.15 MB
	Train Data (Original)  Memory Usage: 5.15 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 6 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Unused Original Features (Count: 1): ['customerid']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['customerid']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  :  2 | ['monthlycharges', 'totalcharges']
		('int', [])    :  2 | ['seniorcitizen', 'tenure']
		('object', []) : 15 | ['gender', 'partner', 'dependents', 'phoneservice', 'multiplelines', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 10 | ['multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', ...]
		('float', [])     :  2 | ['monthlycharges', 'totalcharges']
		('int', [])       :  1 | ['tenure']
		('int', ['bool']) :  6 | ['gender', 'seniorcitizen', 'partner', 'dependents', 'phoneservice', ...]
	0.4s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 0.2 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.56s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.10141987829614604, Train Rows: 4430, Val Rows: 500
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.758	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.732	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMXT ...
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: LightGBM ...
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: RandomForestGini ...
	0.774	 = Validation score   (accuracy)
	2.3s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.784	 = Validation score   (accuracy)
	1.3s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: CatBoost ...
	0.814	 = Validation score   (accuracy)
	5.52s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.774	 = Validation score   (accuracy)
	1.53s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.768	 = Validation score   (accuracy)
	1.44s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.792	 = Validation score   (accuracy)
	8.82s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
	0.782	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.802	 = Validation score   (accuracy)
	6.68s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: WeightedEnsemble_L2 ...
	0.814	 = Validation score   (accuracy)
	0.93s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 31.81s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("agModels-predictchurn/")

CPU times: user 48 s, sys: 2.75 s, total: 50.7 s
Wall time: 31.9 s

In [167]:
predictor.leaderboard(silent=True)

,model,score_val,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.814,0.008851,5.517798,0.008851,5.517798,1,True,5
1,WeightedEnsemble_L2,0.814,0.011298,6.451184,0.002447,0.933386,2,True,11
2,NeuralNetTorch,0.802,0.023423,6.683447,0.023423,6.683447,1,True,10
3,NeuralNetFastAI,0.792,0.021748,8.822634,0.021748,8.822634,1,True,8
4,RandomForestEntr,0.784,0.148517,1.298468,0.148517,1.298468,1,True,4
5,XGBoost,0.782,0.012325,0.691018,0.012325,0.691018,1,True,9
6,RandomForestGini,0.774,0.076403,2.297627,0.076403,2.297627,1,True,3
7,ExtraTreesGini,0.774,0.131301,1.530490,0.131301,1.530490,1,True,6
8,ExtraTreesEntr,0.768,0.079651,1.439148,0.079651,1.439148,1,True,7
9,KNeighborsUnif,0.758,0.024328,0.015150,0.024328,0.015150,1,True,1
10,KNeighborsDist,0.732,0.023120,0.017284,0.023120,0.017284,1,True,2

## Model Evaluation

load test data to make predictions

In [168]:
y_test = test_data[label]

In [169]:
y_test.head()

185     Yes
2715     No
3825     No
1807    Yes
132      No
Name: churn, dtype: object

In [170]:
y_test = test_data[label]  # values to predict

In [171]:
y_test [0:5]

185     Yes
2715     No
3825     No
1807    Yes
132      No
Name: churn, dtype: object

In [172]:
test_data_nolab = test_data.drop(columns=[label])  # delete label column to avoid cheating

In [173]:
test_data_nolab.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.80
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.70
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,No,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.10

In [174]:
save_path

'agModels-predictchurn'

In [175]:
predictor

In [176]:
save_model_predictor = TabularPredictor.load(save_path)

In [177]:
save_model_predictor

In [178]:
y_pred = save_model_predictor.predict(test_data_nolab)

In [179]:
y_pred[0:5]

185     Yes
2715     No
3825     No
1807    Yes
132      No
Name: churn, dtype: object

In [180]:
print("Predictions:  \n", y_pred)
perf = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)

Evaluation: accuracy on test data: 0.8031235210601041
Evaluations on test data:
{
    "accuracy": 0.8031235210601041,
    "balanced_accuracy": 0.7124592194125784,
    "mcc": 0.4686569946165508,
    "f1": 0.5864811133200795,
    "precision": 0.6828703703703703,
    "recall": 0.5139372822299652
}

Predictions:
 185     Yes
2715     No
3825     No
1807    Yes
132      No
       ...
5522    Yes
6377     No
5500     No
2392     No
6705     No
Name: churn, Length: 2113, dtype: object

In [181]:
save_model_predictor.leaderboard(test_data, silent=True)

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.803124,0.814,0.025866,0.008851,5.517798,0.025866,0.008851,5.517798,1,True,5
1,WeightedEnsemble_L2,0.803124,0.814,0.030563,0.011298,6.451184,0.004697,0.002447,0.933386,2,True,11
2,XGBoost,0.803124,0.782,0.090804,0.012325,0.691018,0.090804,0.012325,0.691018,1,True,9
3,NeuralNetTorch,0.801704,0.802,0.082186,0.023423,6.683447,0.082186,0.023423,6.683447,1,True,10
4,NeuralNetFastAI,0.798864,0.792,0.303365,0.021748,8.822634,0.303365,0.021748,8.822634,1,True,8
5,RandomForestGini,0.798391,0.774,0.264374,0.076403,2.297627,0.264374,0.076403,2.297627,1,True,3
6,RandomForestEntr,0.793658,0.784,0.248574,0.148517,1.298468,0.248574,0.148517,1.298468,1,True,4
7,ExtraTreesGini,0.781827,0.774,0.306667,0.131301,1.530490,0.306667,0.131301,1.530490,1,True,6
8,ExtraTreesEntr,0.781354,0.768,0.596075,0.079651,1.439148,0.596075,0.079651,1.439148,1,True,7
9,KNeighborsUnif,0.773308,0.758,0.031147,0.024328,0.015150,0.031147,0.024328,0.015150,1,True,1
10,KNeighborsDist,0.766209,0.732,0.011551,0.023120,0.017284,0.011551,0.023120,0.017284,1,True,2

In [182]:
test_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.80,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.70,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.10,No

## Improving Predictive Performance

Our basic model build took 31.9 seconds, we can improve our model by setting a shorter time limit of 25 seconds

In [159]:
#time_limit = 25

We can also set an evaluation metric

In [160]:
#metric = 'roc_auc'

In [163]:
#save_path = 'agModels-predictchurnimproved'

.. and also preset our models for best quality fit

In [184]:
%%time

time_limit = 20
save_path = 'AutogluonModels'
metric = 'roc_auc'
predictor = TabularPredictor(label, eval_metric=metric).fit(train_data, time_limit=time_limit, presets='best_quality')

No path specified. Models will be saved in: "AutogluonModels/ag-20230219_203642/"
Presets specified: ['best_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=20
Beginning AutoGluon training ... Time limit = 20s
AutoGluon will save models to "AutogluonModels/ag-20230219_203642/"
AutoGluon Version:  0.7.0
Python Version:     3.9.16
Operating System:   Darwin
Platform Machine:   x86_64
Platform Version:   Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
Train Data Rows:    4930
Train Data Columns: 20
Label Column: churn
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['No', 'Yes']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 = Yes, class 0 = No
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5266.57 MB
	Train Data (Original)  Memory Usage: 5.15 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 6 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Unused Original Features (Count: 1): ['customerid']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['customerid']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  :  2 | ['monthlycharges', 'totalcharges']
		('int', [])    :  2 | ['seniorcitizen', 'tenure']
		('object', []) : 15 | ['gender', 'partner', 'dependents', 'phoneservice', 'multiplelines', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 10 | ['multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', ...]
		('float', [])     :  2 | ['monthlycharges', 'totalcharges']
		('int', [])       :  1 | ['tenure']
		('int', ['bool']) :  6 | ['gender', 'seniorcitizen', 'partner', 'dependents', 'phoneservice', ...]
	0.5s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 0.2 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.68s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 19.32s of the 19.31s of remaining time.
	0.731	 = Validation score   (roc_auc)
	0.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 19.24s of the 19.23s of remaining time.
	0.72	 = Validation score   (roc_auc)
	0.01s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 19.16s of the 19.16s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy
	Warning: Exception caused LightGBMXT_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: LightGBM_BAG_L1 ... Training model for up to 19.05s of the 19.05s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy
	Warning: Exception caused LightGBM_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/tescochurn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 18.95s of the 18.95s of remaining time.
	0.8207	 = Validation score   (roc_auc)
	1.31s	 = Training   runtime
	0.4s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 17.1s of the 17.1s of remaining time.
	0.8202	 = Validation score   (roc_auc)
	1.61s	 = Training   runtime
	0.46s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 14.6s of the 14.59s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy
	Ran out of time, early stopping on iteration 93.
	Ran out of time, early stopping on iteration 99.
	Ran out of time, early stopping on iteration 143.
	Ran out of time, early stopping on iteration 141.
	Ran out of time, early stopping on iteration 113.
	Ran out of time, early stopping on iteration 131.
	Ran out of time, early stopping on iteration 178.
	Ran out of time, early stopping on iteration 209.
	0.8428	 = Validation score   (roc_auc)
	13.89s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 0.39s of the 0.39s of remaining time.
	0.8083	 = Validation score   (roc_auc)
	2.32s	 = Training   runtime
	0.49s	 = Validation runtime
Completed 1/20 k-fold bagging repeats ...
Fitting model: WeightedEnsemble_L2 ... Training model for up to 19.32s of the -2.7s of remaining time.
	0.843	 = Validation score   (roc_auc)
	1.27s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 24.03s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20230219_203642/")

CPU times: user 31.8 s, sys: 1.93 s, total: 33.7 s
Wall time: 24.2 s

In [186]:
predictor.leaderboard(test_data, silent=True)

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.860705,0.842965,1.153371,1.004899,18.090163,0.011594,0.001209,1.268352,2,True,7
1,CatBoost_BAG_L1,0.860653,0.842803,0.062715,0.119853,13.890118,0.062715,0.119853,13.890118,1,True,5
2,RandomForestGini_BAG_L1,0.837488,0.820652,0.548476,0.400431,1.309332,0.548476,0.400431,1.309332,1,True,3
3,RandomForestEntr_BAG_L1,0.837081,0.820211,0.522152,0.462974,1.607918,0.522152,0.462974,1.607918,1,True,4
4,ExtraTreesGini_BAG_L1,0.831588,0.808307,0.961456,0.485309,2.320530,0.961456,0.485309,2.320530,1,True,6
5,KNeighborsUnif_BAG_L1,0.751180,0.730969,0.008581,0.013133,0.013325,0.008581,0.013133,0.013325,1,True,1
6,KNeighborsDist_BAG_L1,0.742869,0.720020,0.008434,0.020432,0.014443,0.008434,0.020432,0.014443,1,True,2

Model building results show only 7 models can complete iteration within time limit set

In [91]:
#Bringing it all together

In [187]:
test_data["predicted_churn"] = y_pred

In [188]:
test_data.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,predicted_churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.80,Yes,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.70,No,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,...,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.10,No,No

In [189]:
test_data.sample(10)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,predicted_churn
5936,9418-RUKPH,Female,0,Yes,Yes,38,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,19.95,756.40,No,No
6422,8668-KNZTI,Male,0,No,No,52,Yes,No,DSL,Yes,...,No,No,No,One year,No,Electronic check,53.75,2790.65,No,No
6049,7634-HLQJR,Female,0,Yes,Yes,47,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),20.05,1016.70,No,No
2623,3130-ICDUP,Female,0,No,Yes,2,Yes,Yes,Fiber optic,Yes,...,No,No,No,Month-to-month,No,Credit card (automatic),80.55,188.10,No,No
5589,7253-UVNDW,Female,0,No,No,46,Yes,No,DSL,No,...,Yes,No,No,Two year,No,Credit card (automatic),54.35,2460.15,Yes,No
6388,1963-VAUKV,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.40,20.40,Yes,No
93,6067-NGCEU,Female,0,No,No,65,Yes,Yes,Fiber optic,Yes,...,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),111.05,7107.00,No,No
3973,3441-CGZJH,Female,0,Yes,Yes,43,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,One year,Yes,Credit card (automatic),60.40,2640.55,No,No
5391,8124-NZVGJ,Female,0,No,No,6,No,No phone service,DSL,No,...,Yes,Yes,Yes,One year,Yes,Mailed check,49.25,255.60,No,No
5720,2325-WINES,Female,0,No,No,32,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),104.05,3416.85,No,No